name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Cache Roswell and Scoop
        uses: actions/cache@v4
        with:
          path: |
            ~/.roswell
            ~/AppData/Local/roswell
            ~/scoop/apps/roswell
            ~/scoop/shims
          key: ${{ runner.os }}-roswell-scoop-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-roswell-scoop-
      - name: Install Scoop and Roswell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          iwr -useb get.scoop.sh | iex
          scoop install roswell
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:USERPROFILE\AppData\Local\roswell" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Set up Roswell and SBCL
        shell: pwsh
        run: |
          ros setup
          ros install sbcl
          ros use sbcl-bin
      - name: Run tests with coverage
        shell: pwsh
        run: |
          ros run --load run-tests.lisp --quit
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 7
          if-no-files-found: warn
