name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find release notes file
        id: notes
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $name = "$tag.md"
          $path1 = Join-Path "release-notes" $name
          if (Test-Path $path1) {
            echo "file=$path1" >> $env:GITHUB_OUTPUT
            exit 0
          }
          echo "file=" >> $env:GITHUB_OUTPUT

      - name: Read notes (if any)
        id: read
        if: steps.notes.outputs.file != ''
        shell: pwsh
        run: |
          $content = Get-Content -Raw $env:GITHUB_WORKSPACE\${{ steps.notes.outputs.file }}
          $content = $content -replace "`r`n","`n"
          $content | Out-File -FilePath notes.txt -Encoding utf8
          echo "path=notes.txt" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: ${{ steps.read.outputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
